const { Pais } = require('../models');

const paises = [
  { id: 1, nombre: 'Afganistán', codigo: 'AF' },
  { id: 2, nombre: 'Albania', codigo: 'AL' },
  { id: 3, nombre: 'Alemania', codigo: 'DE' },
  { id: 4, nombre: 'Andorra', codigo: 'AD' },
  { id: 5, nombre: 'Angola', codigo: 'AO' },
  { id: 6, nombre: 'Antigua y Barbuda', codigo: 'AG' },
  { id: 7, nombre: 'Arabia Saudita', codigo: 'SA' },
  { id: 8, nombre: 'Argelia', codigo: 'DZ' },
  { id: 9, nombre: 'Argentina', codigo: 'AR' },
  { id: 10, nombre: 'Armenia', codigo: 'AM' },
  { id: 11, nombre: 'Australia', codigo: 'AU' },
  { id: 12, nombre: 'Austria', codigo: 'AT' },
  { id: 13, nombre: 'Azerbaiyán', codigo: 'AZ' },
  { id: 14, nombre: 'Bahamas', codigo: 'BS' },
  { id: 15, nombre: 'Bangladés', codigo: 'BD' },
  { id: 16, nombre: 'Barbados', codigo: 'BB' },
  { id: 17, nombre: 'Baréin', codigo: 'BH' },
  { id: 18, nombre: 'Bélgica', codigo: 'BE' },
  { id: 19, nombre: 'Belice', codigo: 'BZ' },
  { id: 20, nombre: 'Benín', codigo: 'BJ' },
  { id: 21, nombre: 'Bielorrusia', codigo: 'BY' },
  { id: 22, nombre: 'Birmania', codigo: 'MM' },
  { id: 23, nombre: 'Bolivia', codigo: 'BO' },
  { id: 24, nombre: 'Bosnia y Herzegovina', codigo: 'BA' },
  { id: 25, nombre: 'Botsuana', codigo: 'BW' },
  { id: 26, nombre: 'Brasil', codigo: 'BR' },
  { id: 27, nombre: 'Brunéi', codigo: 'BN' },
  { id: 28, nombre: 'Bulgaria', codigo: 'BG' },
  { id: 29, nombre: 'Burkina Faso', codigo: 'BF' },
  { id: 30, nombre: 'Burundi', codigo: 'BI' },
  { id: 31, nombre: 'Bután', codigo: 'BT' },
  { id: 32, nombre: 'Cabo Verde', codigo: 'CV' },
  { id: 33, nombre: 'Camboya', codigo: 'KH' },
  { id: 34, nombre: 'Camerún', codigo: 'CM' },
  { id: 35, nombre: 'Canadá', codigo: 'CA' },
  { id: 36, nombre: 'Catar', codigo: 'QA' },
  { id: 37, nombre: 'Chad', codigo: 'TD' },
  { id: 38, nombre: 'Chile', codigo: 'CL' },
  { id: 39, nombre: 'China', codigo: 'CN' },
  { id: 40, nombre: 'Chipre', codigo: 'CY' },
  { id: 41, nombre: 'Ciudad del Vaticano', codigo: 'VA' },
  { id: 42, nombre: 'Colombia', codigo: 'CO' },
  { id: 43, nombre: 'Comoras', codigo: 'KM' },
  { id: 44, nombre: 'Corea del Norte', codigo: 'KP' },
  { id: 45, nombre: 'Corea del Sur', codigo: 'KR' },
  { id: 46, nombre: 'Costa de Marfil', codigo: 'CI' },
  { id: 47, nombre: 'Costa Rica', codigo: 'CR' },
  { id: 48, nombre: 'Croacia', codigo: 'HR' },
  { id: 49, nombre: 'Cuba', codigo: 'CU' },
  { id: 50, nombre: 'Dinamarca', codigo: 'DK' },
  { id: 51, nombre: 'Dominica', codigo: 'DM' },
  { id: 52, nombre: 'Ecuador', codigo: 'EC' },
  { id: 53, nombre: 'Egipto', codigo: 'EG' },
  { id: 54, nombre: 'El Salvador', codigo: 'SV' },
  { id: 55, nombre: 'Emiratos Árabes Unidos', codigo: 'AE' },
  { id: 56, nombre: 'Eritrea', codigo: 'ER' },
  { id: 57, nombre: 'Eslovaquia', codigo: 'SK' },
  { id: 58, nombre: 'Eslovenia', codigo: 'SI' },
  { id: 59, nombre: 'España', codigo: 'ES' },
  { id: 60, nombre: 'Estados Unidos', codigo: 'US' },
  { id: 61, nombre: 'Estonia', codigo: 'EE' },
  { id: 62, nombre: 'Etiopía', codigo: 'ET' },
  { id: 63, nombre: 'Filipinas', codigo: 'PH' },
  { id: 64, nombre: 'Finlandia', codigo: 'FI' },
  { id: 65, nombre: 'Fiyi', codigo: 'FJ' },
  { id: 66, nombre: 'Francia', codigo: 'FR' },
  { id: 67, nombre: 'Gabón', codigo: 'GA' },
  { id: 68, nombre: 'Gambia', codigo: 'GM' },
  { id: 69, nombre: 'Georgia', codigo: 'GE' },
  { id: 70, nombre: 'Ghana', codigo: 'GH' },
  { id: 71, nombre: 'Granada', codigo: 'GD' },
  { id: 72, nombre: 'Grecia', codigo: 'GR' },
  { id: 73, nombre: 'Guatemala', codigo: 'GT' },
  { id: 74, nombre: 'Guyana', codigo: 'GY' },
  { id: 75, nombre: 'Guinea', codigo: 'GN' },
  { id: 76, nombre: 'Guinea Ecuatorial', codigo: 'GQ' },
  { id: 77, nombre: 'Guinea-Bisáu', codigo: 'GW' },
  { id: 78, nombre: 'Haití', codigo: 'HT' },
  { id: 79, nombre: 'Honduras', codigo: 'HN' },
  { id: 80, nombre: 'Hungría', codigo: 'HU' },
  { id: 81, nombre: 'India', codigo: 'IN' },
  { id: 82, nombre: 'Indonesia', codigo: 'ID' },
  { id: 83, nombre: 'Irak', codigo: 'IQ' },
  { id: 84, nombre: 'Irán', codigo: 'IR' },
  { id: 85, nombre: 'Irlanda', codigo: 'IE' },
  { id: 86, nombre: 'Islandia', codigo: 'IS' },
  { id: 87, nombre: 'Islas Marshall', codigo: 'MH' },
  { id: 88, nombre: 'Islas Salomón', codigo: 'SB' },
  { id: 89, nombre: 'Israel', codigo: 'IL' },
  { id: 90, nombre: 'Italia', codigo: 'IT' },
  { id: 91, nombre: 'Jamaica', codigo: 'JM' },
  { id: 92, nombre: 'Japón', codigo: 'JP' },
  { id: 93, nombre: 'Jordania', codigo: 'JO' },
  { id: 94, nombre: 'Kazajistán', codigo: 'KZ' },
  { id: 95, nombre: 'Kenia', codigo: 'KE' },
  { id: 96, nombre: 'Kirguistán', codigo: 'KG' },
  { id: 97, nombre: 'Kiribati', codigo: 'KI' },
  { id: 98, nombre: 'Kuwait', codigo: 'KW' },
  { id: 99, nombre: 'Laos', codigo: 'LA' },
  { id: 100, nombre: 'Lesoto', codigo: 'LS' },
  { id: 101, nombre: 'Letonia', codigo: 'LV' },
  { id: 102, nombre: 'Líbano', codigo: 'LB' },
  { id: 103, nombre: 'Liberia', codigo: 'LR' },
  { id: 104, nombre: 'Libia', codigo: 'LY' },
  { id: 105, nombre: 'Liechtenstein', codigo: 'LI' },
  { id: 106, nombre: 'Lituania', codigo: 'LT' },
  { id: 107, nombre: 'Luxemburgo', codigo: 'LU' },
  { id: 108, nombre: 'Madagascar', codigo: 'MG' },
  { id: 109, nombre: 'Malasia', codigo: 'MY' },
  { id: 110, nombre: 'Malaui', codigo: 'MW' },
  { id: 111, nombre: 'Maldivas', codigo: 'MV' },
  { id: 112, nombre: 'Malí', codigo: 'ML' },
  { id: 113, nombre: 'Malta', codigo: 'MT' },
  { id: 114, nombre: 'Marruecos', codigo: 'MA' },
  { id: 115, nombre: 'Mauricio', codigo: 'MU' },
  { id: 116, nombre: 'Mauritania', codigo: 'MR' },
  { id: 117, nombre: 'México', codigo: 'MX' },
  { id: 118, nombre: 'Micronesia', codigo: 'FM' },
  { id: 119, nombre: 'Moldavia', codigo: 'MD' },
  { id: 120, nombre: 'Mónaco', codigo: 'MC' },
  { id: 121, nombre: 'Mongolia', codigo: 'MN' },
  { id: 122, nombre: 'Montenegro', codigo: 'ME' },
  { id: 123, nombre: 'Mozambique', codigo: 'MZ' },
  { id: 124, nombre: 'Namibia', codigo: 'NA' },
  { id: 125, nombre: 'Nauru', codigo: 'NR' },
  { id: 126, nombre: 'Nepal', codigo: 'NP' },
  { id: 127, nombre: 'Nicaragua', codigo: 'NI' },
  { id: 128, nombre: 'Níger', codigo: 'NE' },
  { id: 129, nombre: 'Nigeria', codigo: 'NG' },
  { id: 130, nombre: 'Noruega', codigo: 'NO' },
  { id: 131, nombre: 'Nueva Zelanda', codigo: 'NZ' },
  { id: 132, nombre: 'Omán', codigo: 'OM' },
  { id: 133, nombre: 'Países Bajos', codigo: 'NL' },
  { id: 134, nombre: 'Pakistán', codigo: 'PK' },
  { id: 135, nombre: 'Palaos', codigo: 'PW' },
  { id: 136, nombre: 'Panamá', codigo: 'PA' },
  { id: 137, nombre: 'Papúa Nueva Guinea', codigo: 'PG' },
  { id: 138, nombre: 'Paraguay', codigo: 'PY' },
  { id: 139, nombre: 'Perú', codigo: 'PE' },
  { id: 140, nombre: 'Polonia', codigo: 'PL' },
  { id: 141, nombre: 'Portugal', codigo: 'PT' },
  { id: 142, nombre: 'Reino Unido', codigo: 'GB' },
  { id: 143, nombre: 'República Centroafricana', codigo: 'CF' },
  { id: 144, nombre: 'República Checa', codigo: 'CZ' },
  { id: 145, nombre: 'República de Macedonia del Norte', codigo: 'MK' },
  { id: 146, nombre: 'República del Congo', codigo: 'CG' },
  { id: 147, nombre: 'República Democrática del Congo', codigo: 'CD' },
  { id: 148, nombre: 'República Dominicana', codigo: 'DO' },
  { id: 149, nombre: 'República Sudafricana', codigo: 'ZA' },
  { id: 150, nombre: 'Ruanda', codigo: 'RW' },
  { id: 151, nombre: 'Rumanía', codigo: 'RO' },
  { id: 152, nombre: 'Rusia', codigo: 'RU' },
  { id: 153, nombre: 'Samoa', codigo: 'WS' },
  { id: 154, nombre: 'San Cristóbal y Nieves', codigo: 'KN' },
  { id: 155, nombre: 'San Marino', codigo: 'SM' },
  { id: 156, nombre: 'San Vicente y las Granadinas', codigo: 'VC' },
  { id: 157, nombre: 'Santa Lucía', codigo: 'LC' },
  { id: 158, nombre: 'Santo Tomé y Príncipe', codigo: 'ST' },
  { id: 159, nombre: 'Senegal', codigo: 'SN' },
  { id: 160, nombre: 'Serbia', codigo: 'RS' },
  { id: 161, nombre: 'Seychelles', codigo: 'SC' },
  { id: 162, nombre: 'Sierra Leona', codigo: 'SL' },
  { id: 163, nombre: 'Singapur', codigo: 'SG' },
  { id: 164, nombre: 'Siria', codigo: 'SY' },
  { id: 165, nombre: 'Somalia', codigo: 'SO' },
  { id: 166, nombre: 'Sri Lanka', codigo: 'LK' },
  { id: 167, nombre: 'Suazilandia', codigo: 'SZ' },
  { id: 168, nombre: 'Sudán', codigo: 'SD' },
  { id: 169, nombre: 'Sudán del Sur', codigo: 'SS' },
  { id: 170, nombre: 'Suecia', codigo: 'SE' },
  { id: 171, nombre: 'Suiza', codigo: 'CH' },
  { id: 172, nombre: 'Surinam', codigo: 'SR' },
  { id: 173, nombre: 'Tailandia', codigo: 'TH' },
  { id: 174, nombre: 'Tanzania', codigo: 'TZ' },
  { id: 175, nombre: 'Tayikistán', codigo: 'TJ' },
  { id: 176, nombre: 'Timor Oriental', codigo: 'TL' },
  { id: 177, nombre: 'Togo', codigo: 'TG' },
  { id: 178, nombre: 'Tonga', codigo: 'TO' },
  { id: 179, nombre: 'Trinidad y Tobago', codigo: 'TT' },
  { id: 180, nombre: 'Túnez', codigo: 'TN' },
  { id: 181, nombre: 'Turkmenistán', codigo: 'TM' },
  { id: 182, nombre: 'Turquía', codigo: 'TR' },
  { id: 183, nombre: 'Tuvalu', codigo: 'TV' },
  { id: 184, nombre: 'Ucrania', codigo: 'UA' },
  { id: 185, nombre: 'Uganda', codigo: 'UG' },
  { id: 186, nombre: 'Uruguay', codigo: 'UY' },
  { id: 187, nombre: 'Uzbekistán', codigo: 'UZ' },
  { id: 188, nombre: 'Vanuatu', codigo: 'VU' },
  { id: 189, nombre: 'Venezuela', codigo: 'VE' },
  { id: 190, nombre: 'Vietnam', codigo: 'VN' },
  { id: 191, nombre: 'Yemen', codigo: 'YE' },
  { id: 192, nombre: 'Yibuti', codigo: 'DJ' },
  { id: 193, nombre: 'Zambia', codigo: 'ZM' },
  { id: 194, nombre: 'Zimbabue', codigo: 'ZW' }
];

const seedPaises = async () => {
  try {
    for (const p of paises) {
      await Pais.findOrCreate({ where: { id: p.id }, defaults: p });
    }
    console.log('✅ Países insertados correctamente');
  } catch (error) {
    console.error('❌ Error insertando países:', error);
  } finally {
    process.exit();
  }
};

seedPaises();